services:
  neo4j:
    image: neo4j:5
    container_name: pokemart-neo4j
    ports:
      - "7474:7474" # Painel Web (Browser)
      - "7687:7687" # Conexão da API (Bolt)
    environment:
      - NEO4J_AUTH=neo4j/pokemart2026
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p pokemart2026 'RETURN 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  redis:
    image: redis:7.2.4-alpine
    container_name: pokemart-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokemart-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=minha-chave-secreta-docker-2026
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy

  # ==========================================
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: pokemart-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - api

  # ==========================================
  grafana:
    image: grafana/grafana:10.4.1
    container_name: pokemart-grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  neo4j_data:
  redis_data:
  prometheus_data:
  grafana_data:
