spring:
  application:
    name: pokemart-api

  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      # username: default
      password: ${REDIS_PASSWORD}
      # ssl:
      # enabled: true

  threads:
    virtual:
      enabled: true


api:
  security:
    cookie:
      secure: true
    token:
      secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
  

rate-limit:
  capacity: 50        
  minutes: 1          
  login-capacity: 10  
  login-minutes: 1    

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: pokemart-api