spring:
  application:
    name: pokemart-api

  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      # username: default
      password: ${REDIS_PASSWORD}
      # ssl:
      # enabled: true

logging:
  level:
    "[org.springframework.data.neo4j]": INFO
    "[org.springframework.data.neo4j.cypher]": DEBUG
    "[org.springframework.cache]": TRACE

api:
  security:
    token:
      secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
  

rate-limit:
  capacity: 50        
  minutes: 1          
  login-capacity: 10  
  login-minutes: 1    