spring:
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: ${NEO4J_USER}
      password: ${NEO4J_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

api:
  security:
    token:
      secret: ${JWT_SECRET}
